version: '3.1'

services:
  # admin
  # LecOaToQQNm0cWIMIf
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    env_file:
      - .env
    volumes:
      - ./app:/var/www/html:rw
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    volumes:  # Use utils/dump.php to dump the database
      - ./db:/var/lib/mysql
      - ./dumps:/docker-entrypoint-initdb.d
