version: "3.1"
services:
  # admin
  # LecOaToQQNm0cWIMIf
  wordpress:
    image: wordpress:5.9.1-apache
    restart: always
    ports:
      - "8080:80"
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./app:/var/www/html:rw
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    volumes:  # Use utils/dump.php to dump the database
      - db_data:/var/lib/mysql
      - ./dumps:/docker-entrypoint-initdb.d
  ubuntu:
    image: ubuntu:20.04
    working_dir: /utils
    volumes:
      - ./utils:/utils:rw
    depends_on:
      - db
  # nginx:
  #   image: nginx:1.22.0-alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./nginx/cyrillekossyguine.xyz.conf:/etc/nginx/conf.d/cyrillekossyguine.xyz.conf:ro
  #     - ./var/log/nginx:/var/log/nginx:rw
  #   depends_on:
  #     - wordpress
  #     - db
volumes:
  db_data: {}
