version: "3.1"
services:
  # admin
  # LecOaToQQNm0cWIMIf
  wordpress:
    image: wordpress:5.9.1-apache
    restart: always
    ports:
      - "8090:80"
    env_file:
      - .env
    volumes:
      - ./app:/var/www/html:delegated
      - ./dumps:/dumps:rw
      - ./utils:/utils:ro
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306"
    env_file:
      - .env
    volumes: # Use utils/dump.php to dump the database
      - db_data:/var/lib/mysql
      - ./dumps:/dumps:ro
    working_dir: /
volumes:
  db_data: { }
